# Generated by Django 6.0 on 2026-05-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageTraite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_frame', models.TextField(max_length=25)),
                ('image', models.FileField(upload_to='traitement/')),
                ('date', models.TimeField(auto_now=True)),
            ],
        ),
    ]
