# Generated by Django 6.0 on 2026-05-26 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveservor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reconnus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('source', models.TextField(max_length=25)),
                ('nom', models.TextField(max_length=25)),
                ('heure', models.TimeField(auto_now=True)),
            ],
        ),
    ]
