# Generated by Django 6.0.6 on 2026-10-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveservor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='treated_link',
            field=models.CharField(blank=True, null=True),
        ),
    ]
