# Generated by Django 6.0 on 2026-05-26 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveservor', '0002_reconnus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconnus',
            name='date',
            field=models.DateField(auto_now=True, unique=True),
        ),
    ]
