# Generated by Django 6.0 on 2026-05-26 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveservor', '0003_alter_reconnus_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconnus',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
