# Generated by Django 6.0 on 2026-05-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveservor', '0004_alter_reconnus_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListePresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('file', models.FileField(upload_to='Fichier/')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField(max_length=25)),
                ('photo', models.ImageField(upload_to='image/')),
            ],
        ),
    ]
