# Generated by Django 6.0 on 2026-05-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveservor', '0005_listepresence_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='listepresence',
            name='nom',
            field=models.TextField(default=None, max_length=25),
        ),
    ]
